SUPABASE_URL = "https://tmvttzvmrnlsrnlqjeop.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtdnR0enZtcm5sc3JubHFqZW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MDU4MDAsImV4cCI6MjA3NjE4MTgwMH0.d5LoTW8ne_mT1XigkUgm4ubZudirjYY-wCEID-ZPoKc"
